### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by LightBlueCube** [DBmaoha/nessie.tempfix#1]
之前是从pr上下的tempfix，然后发现上机时训牛还是会崩，然后我把你之前给我的rodeo.gunt放mod里了，就修好了
然后这次是新的训牛bug崩的服，不确定发生啥事，当时我正好在干饭
谢谢啦
[Desktop.zip](https://github.com/DBmaoha/nessie.tempfix/files/9791881/Desktop.zip)

**Comment by DBmaoha** [comment]
因为这个没有修完驯牛
